/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pemilu.Presentation;

import com.mycompany.pemilu.Model.Calon;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class InputPaslonFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputPaslonFrame
     */
    public InputPaslonFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PaslonHeader = new javax.swing.JLabel();
        NomorUrutLabel = new javax.swing.JLabel();
        NomorUrutComboBox = new javax.swing.JComboBox<>();
        NIKKetuaLabel = new javax.swing.JLabel();
        NIKWakilLabel = new javax.swing.JLabel();
        NIKKetuaTextField = new javax.swing.JTextField();
        NIKWakilTextField = new javax.swing.JTextField();
        VisiMisiLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        VisiMisiTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        PaslonHeader.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        PaslonHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaslonHeader.setText("Input Pasangan Calon");

        NomorUrutLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomorUrutLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        NomorUrutLabel.setText("Nomor Urut :");

        NomorUrutComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        NomorUrutComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomorUrutComboBoxActionPerformed(evt);
            }
        });

        NIKKetuaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIKKetuaLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        NIKKetuaLabel.setText("NIK Ketua :");

        NIKWakilLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIKWakilLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        NIKWakilLabel.setText("NIK Wakil Ketua :");

        NIKWakilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIKWakilTextFieldActionPerformed(evt);
            }
        });

        VisiMisiLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VisiMisiLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        VisiMisiLabel.setText("Visi Misi :");

        AddButton.setText("Tambah");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        VisiMisiTextArea.setColumns(20);
        VisiMisiTextArea.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PaslonHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NIKKetuaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomorUrutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIKWakilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VisiMisiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIKKetuaTextField)
                            .addComponent(NIKWakilTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomorUrutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VisiMisiTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE)))))
                .addGap(110, 110, 110))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(PaslonHeader))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BackButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomorUrutLabel)
                    .addComponent(NomorUrutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NIKKetuaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIKKetuaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIKWakilLabel)
                    .addComponent(NIKWakilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VisiMisiLabel)
                        .addComponent(VisiMisiTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomorUrutComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorUrutComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorUrutComboBoxActionPerformed

    private void NIKWakilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIKWakilTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIKWakilTextFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AdminControlFrame acf = new AdminControlFrame();
        
        dispose();
        acf.setVisible(true);
        acf.setLocationRelativeTo(null);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
            // Check if any of the text fields is empty
    if (NIKKetuaTextField.getText().isEmpty() && NIKWakilTextField.getText().isEmpty() && VisiMisiTextArea.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Anda belum mengisi semua form!");
    } else if((!NIKKetuaTextField.getText().isEmpty() && !NIKWakilTextField.getText().isEmpty() && !VisiMisiTextArea.getText().isEmpty()) && NIKKetuaTextField.getText().length() > 8 && NIKWakilTextField.getText().length() > 8){
        // Add your code for processing the form data (if needed)
        // For now, you can show a success message
        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        AdminControlFrame ac = new AdminControlFrame();
        dispose();
        ac.setVisible(true);
        ac.setLocationRelativeTo(null);
        try {
            Calon c = new Calon((int) NomorUrutComboBox.getSelectedItem(), NIKKetuaTextField.getText(), NIKWakilTextField.getText(), VisiMisiTextArea.getText());
            Calon.create(c);
        } catch (SQLException ex) {
            Logger.getLogger(InputPaslonFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }else {
        // Add your code for processing the form data (if needed)
        // For now, you can show a success message
        JOptionPane.showMessageDialog(this, "Minimum karakter NIK ada 8!", "Warning!", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputPaslonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputPaslonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputPaslonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputPaslonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputPaslonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel NIKKetuaLabel;
    private javax.swing.JTextField NIKKetuaTextField;
    private javax.swing.JLabel NIKWakilLabel;
    private javax.swing.JTextField NIKWakilTextField;
    private javax.swing.JComboBox<String> NomorUrutComboBox;
    private javax.swing.JLabel NomorUrutLabel;
    private javax.swing.JLabel PaslonHeader;
    private javax.swing.JLabel VisiMisiLabel;
    private javax.swing.JTextArea VisiMisiTextArea;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
